/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Haseeb
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        
    }
    
      public void close(){
        WindowEvent closeWindow=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        productsLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        customerDealerLabel = new javax.swing.JLabel();
        purchaseLabel = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        rolesLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        cutomerDealerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productsLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        productsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products.png"))); // NOI18N
        productsLabel.setText("PRODUCTS");
        productsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        productsLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        productsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productsLabelMouseClicked(evt);
            }
        });

        userLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users.png"))); // NOI18N
        userLabel.setText("USERS");
        userLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLabelMouseClicked(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        categoryLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/categorynew.png"))); // NOI18N
        categoryLabel.setText("CATEGORY");
        categoryLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        categoryLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        categoryLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryLabelMouseClicked(evt);
            }
        });

        customerDealerLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        customerDealerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerDealerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customerdealer.png"))); // NOI18N
        customerDealerLabel.setText("CUSTOMER DEALER");
        customerDealerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        customerDealerLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        customerDealerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerDealerLabelMouseClicked(evt);
            }
        });

        purchaseLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        purchaseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/purchasingnew.png"))); // NOI18N
        purchaseLabel.setText("PURCHASE");
        purchaseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        purchaseLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        purchaseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseLabelMouseClicked(evt);
            }
        });

        salesLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        salesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salesnew.png"))); // NOI18N
        salesLabel.setText("SALES");
        salesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salesLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salesLabelMouseClicked(evt);
            }
        });

        homeLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 55)); // NOI18N
        homeLabel.setText("HOME");

        rolesLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        rolesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/authorization.png"))); // NOI18N
        rolesLabel.setText("ROLES");
        rolesLabel.setAutoscrolls(true);
        rolesLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rolesLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rolesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rolesLabelMouseClicked(evt);
            }
        });

        stockLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        stockLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/warehouse.png"))); // NOI18N
        stockLabel.setText("STOCK");
        stockLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stockLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        stockLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockLabelMouseClicked(evt);
            }
        });

        logoutButton.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        cutomerDealerLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        cutomerDealerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/customerdealer.png"))); // NOI18N
        cutomerDealerLabel.setText("CUSTOMER DEALER");
        cutomerDealerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutomerDealerLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cutomerDealerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cutomerDealerLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productsLabel)
                        .addGap(1, 1, 1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(homeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(purchaseLabel))
                        .addGap(239, 239, 239)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(customerDealerLabel)
                            .addGap(188, 188, 188))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(rolesLabel)
                            .addGap(252, 252, 252)
                            .addComponent(salesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(107, 107, 107)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stockLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cutomerDealerLabel)
                        .addGap(64, 64, 64))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(userLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoryLabel)
                            .addComponent(userLabel))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salesLabel)
                            .addComponent(rolesLabel))
                        .addGap(148, 148, 148)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stockLabel)
                                    .addComponent(purchaseLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cutomerDealerLabel)
                                .addGap(19, 19, 19)))
                        .addComponent(customerDealerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(1021, 1021, 1021))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_userLabelMouseClicked

    private void categoryLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_categoryLabelMouseClicked

    private void rolesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolesLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_rolesLabelMouseClicked

    private void productsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productsLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_productsLabelMouseClicked

    private void purchaseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_purchaseLabelMouseClicked

    private void stockLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_stockLabelMouseClicked

    private void salesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_salesLabelMouseClicked

    private void customerDealerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDealerLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_customerDealerLabelMouseClicked

    private void cutomerDealerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutomerDealerLabelMouseClicked
        // TODO add your handling code here:
        close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_cutomerDealerLabelMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
          close();
        CustomerDealerFrame customerDealerFrame=new CustomerDealerFrame();
        customerDealerFrame.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel customerDealerLabel;
    private javax.swing.JLabel cutomerDealerLabel;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JLabel purchaseLabel;
    private javax.swing.JLabel rolesLabel;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
